db:
    host: localhost
    port: 27017

es:
    mapping: v1
    indexName: eucsv
    host: localhost
    port: 9200

mongodb:
    host: localhost
    port: 27018

odpw:
    apiurl: http://data.wu.ac.at/portalwatch/api/v1/

heideltime: heideltime-standalone

twentythree: null