es:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
  ports:
   - "9200:9200"
  environment:
   - "ES_JAVA_OPTS=-Xms10g -Xmx10g"
  volumes:
   - /home/csv/es-index/esdata:/usr/share/elasticsearch/data
