es:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
  ports:
   - "9200:9200"
  environment:
   - "ES_JAVA_OPTS=-Xms10g -Xmx10g"
   - xpack.security.enabled=false
   - xpack.license.self_generated.type=basic
  volumes:
   - /home/csv/es-index/esdata:/usr/share/elasticsearch/data